name: simple ci workflow
on:
  push:
    branches:
      - master
jobs:
  mytestbuild:
    runs-on: ubuntu-latest

    steps:
      - name: PRINT A TEST MESSAGE
        run: echo "hello from $GITHUB_ACTOR!"
